mautic/docroot/app/bundles/DynamicContentBundle/Form/Type/DynamicContentListType.php
<?php

namespace Mautic\DynamicContentBundle\Form\Type;

use Mautic\CoreBundle\Form\Type\EntityLookupType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\OptionsResolver\Options;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * @extends AbstractType<mixed>
 */
class DynamicContentListType extends AbstractType
{
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults(
            [
                'modal_route'         => 'mautic_dynamicContent_action',
                'modal_header'        => 'mautic.dynamicContent.header.new',
                'model'               => 'dynamicContent',
                'model_lookup_method' => 'getLookupResults',
                'lookup_arguments'    => fn (Options $options): array => [
                    'type'    => 'dynamicContent',
                    'filter'  => '$data',
                    'limit'   => 0,
                    'start'   => 0,
                    'options' => [
                        'top_level'  => $options['top_level'],
                        'ignore_ids' => $options['ignore_ids'],
                        'where'      => $options['where'],
                    ],
                ],
                'ajax_lookup_action' => function (Options $options): string {
                    $query = [
                        'top_level'  => $options['top_level'],
                        'ignore_ids' => $options['ignore_ids'],
                        'where'      => $options['where'],
                    ];

                    return 'dynamicContent:getLookupChoiceList&'.http_build_query($query);
                },
                'multiple'   => false,
                'required'   => false,
                'top_level'  => 'translation',
                'ignore_ids' => [],
                'where'      => '',
            ]
        );
    }

    /**
     * @return string
     */
    public function getBlockPrefix()
    {
        return 'dwc_list';
    }

    /**
     * @return string
     */
    public function getParent()
    {
        return EntityLookupType::class;
    }
}

mautic/docroot/app/bundles/DynamicContentBundle/Controller/DynamicContentController.php
<?php

namespace Mautic\DynamicContentBundle\Controller;

use Mautic\CoreBundle\Controller\FormController;
use Mautic\CoreBundle\Form\Type\DateRangeType;
use Mautic\CoreBundle\Model\AuditLogModel;
use Mautic\DynamicContentBundle\Entity\DynamicContent;
use Mautic\DynamicContentBundle\Model\DynamicContentModel;
use Mautic\PageBundle\Model\PageModel;
use Mautic\PageBundle\Model\TrackableModel;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class DynamicContentController extends FormController
{
    protected function getPermissions(): array
    {
        return (array) $this->security->isGranted(
            [
                'dynamiccontent:dynamiccontents:viewown',
                'dynamiccontent:dynamiccontents:viewother',
                'dynamiccontent:dynamiccontents:create',
                'dynamiccontent:dynamiccontents:editown',
                'dynamiccontent:dynamiccontents:editother',
                'dynamiccontent:dynamiccontents:deleteown',
                'dynamiccontent:dynamiccontents:deleteother',
                'dynamiccontent:dynamiccontents:publishown',
                'dynamiccontent:dynamiccontents:publishother',
            ],
            'RETURN_ARRAY'
        );
    }

    public function indexAction(Request $request, $page = 1)
    {
        $model = $this->getModel('dynamicContent');

        $permissions = $this->getPermissions();

        if (!$permissions['dynamiccontent:dynamiccontents:viewown'] && !$permissions['dynamiccontent:dynamiccontents:viewother']) {
            return $this->accessDenied();
        }

        $this->setListFilters();

        $limit = $request->getSession()->get('mautic.dynamicContent.limit', $this->coreParametersHelper->get('default_pagelimit'));
        $start = (1 === $page) ? 0 : (($page - 1) * $limit);
        if ($start < 0) {
            $start = 0;
        }

        // fetch
        $search = $request->get('search', $request->getSession()->get('mautic.dynamicContent.filter', ''));
        $request->getSession()->set('mautic.dynamicContent.filter', $search);

        $filter = [
            'string' => $search,
            'force'  => [
                ['column' => 'e.variantParent', 'expr' => 'isNull'],
                ['column' => 'e.translationParent', 'expr' => 'isNull'],
            ],
        ];

        $orderBy    = $request->getSession()->get('mautic.dynamicContent.orderby', 'e.name');
        $orderByDir = $request->getSession()->get('mautic.dynamicContent.orderbydir', 'DESC');

        $entities = $model->getEntities(
            [
                'start'      => $start,
                'limit'      => $limit,
                'filter'     => $filter,
                'orderBy'    => $orderBy,
                'orderByDir' => $orderByDir,
            ]
        );

        // set what page currently on so that we can return here after form submission/cancellation
        $request->getSession()->set('mautic.dynamicContent.page', $page);

        $tmpl = $request->isXmlHttpRequest() ? $request->get('tmpl', 'index') : 'index';

        // retrieve a list of categories
        $pageModel  = $this->getModel('page');
        \assert($pageModel instanceof PageModel);
        $categories = $pageModel->getLookupResults('category', '', 0);

        return $this->delegateView(
            [
                'contentTemplate' => '@MauticDynamicContent/DynamicContent/list.html.twig',
                'passthroughVars' => [
                    'activeLink'    => '#mautic_dynamicContent_index',
                    'mauticContent' => 'dynamicContent',
                    'route'         => $this->generateUrl('mautic_dynamicContent_index', ['page' => $page]),
                ],
                'viewParameters' => [
                    'searchValue' => $search,
                    'items'       => $entities,
                    'categories'  => $categories,
                    'page'        => $page,
                    'limit'       => $limit,
                    'permissions' => $permissions,
                    'model'       => $model,
                    'tmpl'        => $tmpl,
                ],
            ]
        );
    }

    public function newAction(Request $request, $entity = null)
    {
        if (!$this->security->isGranted('dynamiccontent:dynamiccontents:create')) {
            return $this->accessDenied();
        }

        if (!$entity instanceof DynamicContent) {
            $entity = new DynamicContent();
        }

        $model = $this->getModel('dynamicContent');
        \assert($model instanceof DynamicContentModel);
        $method       = $request->getMethod();
        $page         = $request->getSession()->get('mautic.dynamicContent.page', 1);
        $retUrl       = $this->generateUrl('mautic_dynamicContent_index', ['page' => $page]);
        $action       = $this->generateUrl('mautic_dynamicContent_action', ['objectAction' => 'new']);
        $dwc          = $request->request->get('dwc') ?? [];
        $updateSelect = 'POST' === $method
            ? ($dwc['updateSelect'] ?? false)
            : $request->get('updateSelect', false);
        $form         = $model->createForm($entity, $this->formFactory, $action, ['update_select' => $updateSelect]);

        if (Request::METHOD_POST === $method) {
            $valid = false;

            if (!$cancelled = $this->isFormCancelled($form)) {
                if ($valid = $this->isFormValid($form)) {
                    $model->saveEntity($entity);

                    $this->addFlashMessage(
                        'mautic.core.notice.created',
                        [
                            '%name%'      => $entity->getName(),
                            '%menu_link%' => 'mautic_dynamicContent_index',
                            '%url%'       => $this->generateUrl(
                                'mautic_dynamicContent_action',
                                [
                                    'objectAction' => 'edit',
                                    'objectId'     => $entity->getId(),
                                ]
                            ),
                        ]
                    );

                    if ($this->getFormButton($form, ['buttons', 'save'])->isClicked()) {
                        $viewParameters = [
                            'objectAction' => 'view',
                            'objectId'     => $entity->getId(),
                        ];
                        $retUrl   = $this->generateUrl('mautic_dynamicContent_action', $viewParameters);
                        $template = 'Mautic\DynamicContentBundle\Controller\DynamicContentController::viewAction';
                    } else {
                        // return edit view so that all the session stuff is loaded
                        return $this->editAction($request, $entity->getId(), true);
                    }
                }
            } else {
                $viewParameters = ['page' => $page];
                $retUrl         = $this->generateUrl('mautic_dynamicContent_index', $viewParameters);
                $template       = 'Mautic\DynamicContentBundle\Controller\DynamicContentController::indexAction';
            }

            $passthrough = [
                'activeLink'    => '#mautic_dynamicContent_index',
                'mauticContent' => 'dynamicContent',
            ];

            // Check to see if this is a popup
            if (isset($form['updateSelect'])) {
                $template    = false;
                $passthrough = array_merge(
                    $passthrough,
                    [
                        'updateSelect' => $form['updateSelect']->getData(),
                        'id'           => $entity->getId(),
                        'name'         => $entity->getName(),
                        'group'        => $entity->getLanguage(),
                    ]
                );
            }

            if ($cancelled || ($valid && $this->getFormButton($form, ['buttons', 'save'])->isClicked())) {
                return $this->postActionRedirect(
                    [
                        'returnUrl'       => $retUrl,
                        'viewParameters'  => $viewParameters,
                        'contentTemplate' => $template,
                        'passthroughVars' => $passthrough,
                    ]
                );
            } elseif ($valid && !$cancelled) {
                return $this->editAction($request, $entity->getId(), true);
            }
        }

        $passthrough['route'] = $action;

        return $this->delegateView(
            [
                'viewParameters' => [
                    'form' => $form->createView(),
                ],
                'contentTemplate' => '@MauticDynamicContent/DynamicContent/form.html.twig',
                'passthroughVars' => $passthrough,
            ]
        );
    }

    /**
     * Generate's edit form and processes post data.
     *
     * @param bool|false $ignorePost
     *
     * @return array|JsonResponse|RedirectResponse|Response
     */
    public function editAction(Request $request, $objectId, $ignorePost = false)
    {
        /** @var DynamicContentModel $model */
        $model  = $this->getModel('dynamicContent');
        $entity = $model->getEntity($objectId);
        $page   = $request->getSession()->get('mautic.dynamicContent.page', 1);
        $retUrl = $this->generateUrl('mautic_dynamicContent_index', ['page' => $page]);

        $postActionVars = [
            'returnUrl'       => $retUrl,
            'viewParameters'  => ['page' => $page],
            'contentTemplate' => 'Mautic\DynamicContentBundle\Controller\DynamicContentController::indexAction',
            'passthroughVars' => [
                'activeLink'    => '#mautic_dynamicContent_index',
                'mauticContent' => 'dynamicContent',
            ],
        ];

mautic/docroot/app/bundles/DynamicContentBundle/Resources/views/DynamicContent/_list.html.twig
{#
  Variables
    - searchValue
    - items (\Mautic\DynamicContentBundle\Entity\DynamicContent[])
    - categories
    - page
    - limit
    - permissions
    - model
    - tmpl
#}
{% if items|length > 0 %}
    <div class="table-responsive page-list">
        <table class="table table-hover dwctable-list" id="dwcTable">
            <thead>
            <tr>
                {{ include('@MauticCore/Helper/tableheader.html.twig', {
                        'checkall': 'true',
                        'target': '#dwcTable',
                        'routeBase': 'dynamicContent',
                        'templateButtons': {
                            'delete': permissions['dynamiccontent:dynamiccontents:deleteown'] or permissions['dynamiccontent:dynamiccontents:deleteother'],
                        },
                }) }}

                {{ include('@MauticCore/Helper/tableheader.html.twig', {
                        'sessionVar': 'dynamicContent',
                        'orderBy': 'e.name',
                        'text': 'mautic.core.name',
                        'class': 'col-dwc-name',
                        'default': true,
                }) }}

                {{ include('@MauticCore/Helper/tableheader.html.twig', {
                        'sessionVar': 'dynamicContent',
                        'orderBy': 'e.slotName',
                        'text': 'mautic.dynamicContent.label.slot_name',
                        'class': 'col-dwc-slotname visible-md visible-lg',
                }) }}

                {{ include('@MauticCore/Helper/tableheader.html.twig', {
                        'sessionVar': 'dynamicContent',
                        'orderBy': 'c.title',
                        'text': 'mautic.core.category',
                        'class': 'col-dwc-category visible-md visible-lg',
                }) }}

                {{ include('@MauticCore/Helper/tableheader.html.twig', {
                        'sessionVar': 'dynamicContent',
                        'orderBy': 'e.id',
                        'text': 'mautic.core.id',
                        'class': 'col-dwc-id visible-md visible-lg',
                }) }}
            </tr>
            </thead>
            <tbody>
            {% for item in items %}
                <tr>
                    <td>
                        {{ include('@MauticCore/Helper/list_actions.html.twig', {
                                'item': item,
                                'templateButtons': {
                                    'edit': securityHasEntityAccess(permissions['dynamiccontent:dynamiccontents:editown'], permissions['dynamiccontent:dynamiccontents:editother'], item.createdBy),
                                    'clone': permissions['dynamiccontent:dynamiccontents:create'],
                                    'delete': securityHasEntityAccess(permissions['dynamiccontent:dynamiccontents:deleteown'], permissions['dynamiccontent:dynamiccontents:deleteother'], item.createdBy),
                                },
                                'routeBase': 'dynamicContent',
                                'nameGetter': 'getName',
                        }) }}
                    </td>
                    <td>
                        {{ include('@MauticCore/Helper/publishstatus_icon.html.twig', {'item': item, 'model': 'dynamicContent'}) }}
                        <a href="{{ url('mautic_dynamicContent_action', {'objectAction': 'view', 'objectId': item.id}) }}" data-toggle="ajax">
                            {{ item.name }}
                            {% if item.isVariant or item.isTranslation %}
                                <span>
                                  {% if item.isVariant %}
                                    <span data-toggle="tooltip" title="{{ 'mautic.core.icon_tooltip.ab_test'|trans }}"><i class="fa fa-fw fa-sitemap"></i></span>
                                  {% endif %}
                                  {% if item.isTranslation %}
                                    <span data-toggle="tooltip" title="{{ 'mautic.core.icon_tooltip.translation'|trans }}"><i class="fa fa-fw fa-language"></i></span>
                                  {% endif %}
                                 </span>
                            {% endif %}
                        </a>
                    </td>
                    <td class="visible-md visible-lg">{{ item.slotName }}</td>
                    <td class="visible-md visible-lg">
                        {% set catName = item.category is not empty ? item.category.title : 'mautic.core.form.uncategorized'|trans %}
                        {% set color = item.category is not empty ? '#' ~ item.category.color : 'inherit' %}
                        <span style="white-space: nowrap;">
                          <span class="label label-default pa-4" style="border: 1px solid #d5d5d5; background: {{ color }};"> </span>
                          <span>{{ catName }}</span>
                        </span>
                    </td>
                    <td class="visible-md visible-lg">{{ item.id }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="panel-footer">
            {{ include('@MauticCore/Helper/pagination.html.twig', {
                    'totalItems': items|length,
                    'page': page,
                    'limit': limit,
                    'menuLinkId': 'mautic_dynamicContent_index',
                    'baseUrl': url('mautic_dynamicContent_index'),
                    'sessionVar': 'dynamicContent',
            }) }}
        </div>
    </div>
{% else %}
    {{ include('@MauticCore/Helper/noresults.html.twig') }}
{% endif %}

mautic/docroot/app/bundles/DynamicContentBundle/Resources/views/DynamicContent/details.html.twig
{#
#}
{% extends (not isEmbedded) ? '@MauticCore/Default/content.html.twig' : '@MauticCore/Default/raw_output.html.twig' %}

{% block mauticContent 'dynamicContent' %}

{% block headerTitle entity.name %}

{% block publishStatus include('@MauticCore/Helper/publishstatus_badge.html.twig', {'entity': entity}) %}

{% block actions include('@MauticCore/Helper/page_actions.html.twig', {
    'item': entity,
    'customButtons': customButtons|default([]),
    'templateButtons': {
        'edit': securityHasEntityAccess(permissions['dynamiccontent:dynamiccontents:editown'], permissions['dynamiccontent:dynamiccontents:editother'], entity.createdBy),
        'clone': permissions['dynamiccontent:dynamiccontents:create'],
        'delete': securityHasEntityAccess(permissions['dynamiccontent:dynamiccontents:deleteown'], permissions['dynamiccontent:dynamiccontents:deleteother'], entity.createdBy),
        'close': securityHasEntityAccess(permissions['dynamiccontent:dynamiccontents:viewown'], permissions['dynamiccontent:dynamiccontents:viewother'], entity.createdBy),
    },
    'routeBase': 'dynamicContent',
})  %}

{% block content %}
  {%- set translationContent = include('@MauticCore/Translation/index.html.twig', {
          'activeEntity': entity,
          'translations': translations,
          'model': 'dynamicContent',
          'actionRoute': 'mautic_dynamicContent_action',
  })|trim -%}
  {%- set showTranslations = translationContent is not empty -%}

  <!-- start: box layout -->
  <div class="box-layout">
      <!-- left section -->
      <div class="col-md-9 height-auto">
          <div>
              <!-- page detail header -->
              <div class="pr-md pl-md pt-lg pb-lg">
                  <div class="box-layout">
                      <div class="col-xs-10">
                          <div class="text-muted">{{ entity.description|purify }}</div>
                          {% if entity.isVariant(true) %}
                              <div class="small">
                                  <a href="{{ path('mautic_dynamicContent_action', {'objectAction': 'view', 'objectId': variants.parent.id}) }}" data-toggle="ajax">
                                      {{ 'mautic.core.variant_of'|trans({'%parent%': variants.parent.name}) }}
                                  </a>
                              </div>
                          {% endif %}
                          {% if entity.isTranslation(true) %}
                              <div class="small">
                                  <a href="{{ path('mautic_dynamicContent_action', {'objectAction': 'view', 'objectId': translations.parent.id}) }}" data-toggle="ajax">
                                      {{ 'mautic.core.translation_of'|trans({'%parent%': translations.parent.name}) }}
                                  </a>
                              </div>
                          {% endif %}
                          {% if not entity.isCampaignBased %}
                              <div class="small">
                                  {{ 'mautic.dynamicContent.header.is_filter_based'|trans({'%slot%': entity.slotName}) }}
                              </div>
                          {% endif %}
                      </div>
                  </div>
              </div>
              <!--/ page detail header -->
              <!-- page detail collapseable -->
              <div class="collapse" id="page-details">
                  <div class="pr-md pl-md pb-md">
                      <div class="panel shd-none mb-0">
                          <table class="table table-hover mb-0">
                              <tbody>
                              {{ include('@MauticCore/Helper/details.html.twig', {'entity': entity}) }}
                              <tr>
                                  <td width="20%"><span class="fw-b textTitle">{{ 'mautic.dynamicContent.slot.campaign'|trans }}</span></td>
                                  <td>{{ entity.isCampaignBased ? 'Yes' : 'No' }}</td>
                              </tr>
                              {% if not entity.isCampaignBased %}
                                <tr>
                                    <td width="20%"><span class="fw-b textTitle">{{ 'mautic.dynamicContent.label.slot_name'|trans }}</span></td>
                                    <td>{{ entity.slotName }}</td>
                                </tr>
                              {% endif %}
                              </tbody>
                          </table>
                      </div>
                  </div>
              </div>
              <!--/ page detail collapseable -->
          </div>
          <div>
              <!-- page detail collapseable toggler -->
              <div class="hr-expand nm">
                  <span data-toggle="tooltip" title="Detail">
                      <a href="javascript:void(0)" class="arrow text-muted collapsed" data-toggle="collapse" data-target="#page-details">
                          <span class="caret"></span>
                          {{ 'mautic.core.details'|trans }}
                      </a>
                  </span>
              </div>
              <!--/ page detail collapseable toggler -->

              <!-- some stats -->
              <div class="pa-md">
                  <div class="row">
                      <div class="col-sm-12">
                          <div class="panel">
                              <div class="panel-body box-layout">
                                  <div class="col-md-3 va-m">
                                      <h5 class="text-white dark-md fw-sb mb-xs">
                                          <span class="fa fa-line-chart"></span>
                                          {{ 'mautic.dynamicContent.views'|trans }}
                                      </h5>
                                  </div>
                                  <div class="col-md-9 va-m">
                                      {{ include('@MauticCore/Helper/graph_dateselect.html.twig', {'dateRangeForm': dateRangeForm, 'class': 'pull-right'}) }}
                                  </div>
                              </div>
                              <div class="pt-0 pl-15 pb-10 pr-15">
                                  {{ include('@MauticCore/Helper/chart.html.twig', {'chartData': entityViews, 'chartType': 'line', 'chartHeight': 300}) }}
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <!--/ stats -->

              {{ customContent('details.stats.graph.below', _context) }}

              <!-- tabs controls -->
              <ul class="nav nav-tabs pr-md pl-md">
                  <li class="active">
                      <a href="#clicks-container" role="tab" data-toggle="tab">
                          {{ 'mautic.trackable.click_counts'|trans }}
                      </a>
                  </li>
                  {% if showTranslations %}
                  <li class>
                      <a href="#translation-container" role="tab" data-toggle="tab">
                          {{ 'mautic.core.translations'|trans }}
                      </a>
                  </li>
                  {% endif %}
              </ul>
              <!--/ tabs controls -->
          </div>
          <!-- start: tab-content -->
          <div class="tab-content pa-md">
              <div class="tab-pane active active bdr-w-0" id="clicks-container">
                  {{ include('@MauticPage/Trackable/click_counts.html.twig', {'trackables': trackables, 'entity': entity, 'channel': 'dynamicContent'}) }}

              </div>
              <!-- #translation-container -->
              {% if showTranslations %}
                  <div class="tab-pane bdr-w-0" id="translation-container">
                      {{ translationContent|raw }}
                  </div>
              {% endif %}
              <!--/ #translation-container -->
          </div>
          <!-- end: tab-content -->
      </div>
      <!--/ left section -->

      <!-- right section -->
      <div class="col-md-3 bdr-l height-auto">
          <hr class="hr-w-2" style="width:50%">
          <!-- recent activity -->
          {{ include('@MauticCore/Helper/recentactivity.html.twig', {'logs': logs}) }}
      </div>
      <!--/ right section -->
  </div>

  <!--/ end: box layout -->
{% endblock %}

mautic/docroot/app/bundles/DynamicContentBundle/Resources/views/DynamicContent/list.html.twig
{#
  Variables
    - searchValue
    - items (\Mautic\DynamicContentBundle\Entity\DynamicContent[])
    - categories
    - page
    - limit
    - permissions
    - model
    - tmpl
#}
{%- set isIndex = 'index' == tmpl -%}
{%- set tmpl = 'list' -%}
{% extends isIndex ? '@MauticCore/Default/content.html.twig' : '@MauticCore/Default/raw_output.html.twig' %}

{% block mauticContent 'dynamicContent' %}

{% block headerTitle 'mautic.dynamicContent.dynamicContents'|trans %}

{% block actions %}
    {{ include('@MauticCore/Helper/page_actions.html.twig', {
            'templateButtons': {
                'new': permissions['dynamiccontent:dynamiccontents:create'],
            },
            'routeBase': 'dynamicContent',
    }) }}
{% endblock %}

{% block content %}
  {% if isIndex %}
    <div class="panel panel-default bdr-t-wdh-0 mb-0">
        {{ include('@MauticCore/Helper/list_toolbar.html.twig', {
                'searchValue': searchValue,
                'searchHelp': 'mautic.page.help.searchcommands',
                'action': currentRoute,
        }) }}
        <div class="page-list">
          {{ include('@MauticDynamicContent/DynamicContent/_list.html.twig') }}
        </div>
    </div>
  {% else %}
    {{ include('@MauticDynamicContent/DynamicContent/_list.html.twig') }}
  {% endif %}
{% endblock %}